### ISSUE TITLE
Uncaught SyntaxError: Variable '_requestMIDIAccess' has already been declared WebMIDIAPI.js:104

### ISSUE THREAD

**Issue by pbaille** [ryoyakawai/WebMIDIAPIWrapper#1]
Hi,

I' ve got this error when open the demo,

Uncaught SyntaxError: Variable '_requestMIDIAccess' has already been declared WebMIDIAPI.js:104
navigator.requestMIDIAccess is NOT a function.

I've got JAZZPlugin installed

**Comment by laszlogal** [comment]
Hello,
I am trying the Live Demo on Widows 8.0 and Windows 8.1 with Chrome 43 (jazz plugin also installed btw), but Output select is empty, no Microsoft GS Wavetable synth or such. Midi is allowed for that page. It works perfectly on mac. What should I do? Thanks
